language: java

install: travis_wait 40 mvn -q clean install -Dgib.enabled=true

jdk:
  - oraclejdk8
  
sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
  - .git
  - .autoconf
  - $HOME/.m2

